USE [League]
GO

/****** Object:  Table [dbo].[Coach]    Script Date: 08.06.2019 16:48:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Coach](
	[CoachID] [smallint] NOT NULL,
	[Name] [varchar](30) NOT NULL,
	[Surname] [varchar](50) NOT NULL,
	[BirthDate] [date] NULL,
	[Nationality] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[CoachID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[CoachID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[Coach]  WITH CHECK ADD CHECK  (([BirthDate]<=getdate()))
GO

ALTER TABLE [dbo].[Coach]  WITH CHECK ADD CHECK  (([CoachID]>(0)))
GO

ALTER TABLE [dbo].[Coach]  WITH CHECK ADD CHECK  (([Name]<>''))
GO

ALTER TABLE [dbo].[Coach]  WITH CHECK ADD CHECK  (([Nationality]<>''))
GO

ALTER TABLE [dbo].[Coach]  WITH CHECK ADD CHECK  (([Surname]<>''))
GO


