USE [League]
GO

/****** Object:  Table [dbo].[Goal]    Script Date: 08.06.2019 16:49:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Goal](
	[GoalID] [smallint] NOT NULL,
	[PlayerID] [smallint] NOT NULL,
	[GoalTime] [time](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[GoalID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[GoalID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Goal]  WITH CHECK ADD CHECK  (([GoalID]>(0)))
GO

ALTER TABLE [dbo].[Goal]  WITH CHECK ADD CHECK  (([PlayerID]>(0)))
GO


