USE [League]
GO

/****** Object:  Table [dbo].[Team]    Script Date: 08.06.2019 16:53:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Team](
	[TeamID] [smallint] NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Strength] [smallint] NULL,
PRIMARY KEY CLUSTERED 
(
	[TeamID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[TeamID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[Team]  WITH CHECK ADD CHECK  (([Name]<>''))
GO

ALTER TABLE [dbo].[Team]  WITH CHECK ADD CHECK  (([Strength]>(0) AND [Strength]<(40)))
GO

ALTER TABLE [dbo].[Team]  WITH CHECK ADD CHECK  (([TeamID]>(0)))
GO


