USE [master]
GO

/****** Object:  Database [League]    Script Date: 08.06.2019 16:46:53 ******/
CREATE DATABASE [League]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'League', FILENAME = N'd:\Program Files\SQL\MSSQL11.SQLEXPRESS\MSSQL\DATA\League.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'League_log', FILENAME = N'd:\Program Files\SQL\MSSQL11.SQLEXPRESS\MSSQL\DATA\League_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [League] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [League].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [League] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [League] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [League] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [League] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [League] SET ARITHABORT OFF 
GO

ALTER DATABASE [League] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [League] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [League] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [League] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [League] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [League] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [League] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [League] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [League] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [League] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [League] SET  DISABLE_BROKER 
GO

ALTER DATABASE [League] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [League] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [League] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [League] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [League] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [League] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [League] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [League] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [League] SET  MULTI_USER 
GO

ALTER DATABASE [League] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [League] SET DB_CHAINING OFF 
GO

ALTER DATABASE [League] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [League] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [League] SET  READ_WRITE 
GO


